### ISSUE TITLE
Inserting a variable in a markup sentence creates a false positive "space before the full stop"

### ISSUE THREAD

**Issue by Andrew15-5** [antonWetzel/typst-languagetool#10]
The code (part of it):

```typst
The goal is #goal.

Conclusions: #conclusions.
```

The false positive mistake:

```
Don’t put a space before the full stop. [COMMA_PARENTHESIS_WHITESPACE]
```

![image](https://github.com/antonWetzel/typst-languagetool/assets/37143421/07f47ecb-39f1-437c-a490-b05004b698f9)

**Comment by antonWetzel** [comment]
Similar problem like https://github.com/antonWetzel/typst-languagetool/issues/13.
On AST level it is hard to know what code does.

**Comment by antonWetzel** [comment]
Spellchecking is now after the document compilation, so this should not happen anymore.
If the issue still exits, please reopen the issue.
