### ISSUE TITLE
A false positive "possible spelling mistake"

### ISSUE THREAD

**Issue by Andrew15-5** [antonWetzel/typst-languagetool#11]
This works ok:

```typst
#diagram({
  node(e1)[Something][1]
  node(e2)[Something][2]
})
```

This does not:

```typst
#diagram({
  node(e1)[Something][]
  node(e2)[Something][]
})
```

```
Possible spelling mistake found. [MORFOLOGIK_RULE_EN_US]
```

![image](https://github.com/antonWetzel/typst-languagetool/assets/37143421/c6c0aa1d-d320-46bb-87c4-f332a44258c0)

**Comment by Andrew15-5** [comment]
Nope, this also gives the same error:

```typst
#diagram({
  node(e1)[Something]
  node(e2)[Something]
})
```

**Comment by antonWetzel** [comment]
At the moment the default between content blocks is nothing.

To fix this error the rule
```json5
"functions": {
  "node": {
    "after_argument": "\n\n", // seperate arguments by one empty line
  },
},
```
should work.

At the moment custom rules overwrite the default rules, so `table`, ... will error.
I don't want to add rules for not core functions, but maybe I will for default packges in the future.

I am working on some context system, where seperators like `top-level -> ""` or `diagram.* -> "\n\n"` are possible.

**Comment by antonWetzel** [comment]
Spellchecking is now after the document compilation, so this should not happen anymore.
If the issue still exits, please reopen the issue.
