### ISSUE TITLE
Error when using en/em-dash special syntax (`--`/`---`)

### ISSUE THREAD

**Issue by Andrew15-5** [antonWetzel/typst-languagetool#12]
```typ
Word one --- word.
```

```
It seems like there are too many consecutive spaces here. [CONSECUTIVE_SPACES]
```

![image](https://github.com/antonWetzel/typst-languagetool/assets/37143421/58361c4c-df0d-4e61-862f-38b3a7a8dc43)

**Comment by antonWetzel** [comment]
Should be fixed by https://github.com/antonWetzel/typst-languagetool/commit/a1da91de84db718adac0f45595ea23a0088a957d.
