### ISSUE TITLE
Unpaired quote error caused by prepending `〜` (or letters) to the left quote

### ISSUE THREAD

**Issue by Andrew15-5** [antonWetzel/typst-languagetool#14]
```typ
〜""
```

```
Diagnostics:
1. Unpaired symbol: '"' seems to be missing [EN_UNPAIRED_QUOTES]
```

![image](https://github.com/antonWetzel/typst-languagetool/assets/37143421/fdd69eeb-f2ed-4023-acd0-3d2f453a12bf)

![image](https://github.com/antonWetzel/typst-languagetool/assets/37143421/f5de3c86-04ca-4ff2-b461-5a4c656e0608)

I use it as a workaround as `set par(first-line-indent: indent)` doesn't work for the first paragraph:

```typ
#show "〜": h(1.25cm)
```

I think it's the first time I'm quoting something at the beginning of the first paragraph (whole paragraph), so such usage is pretty rare. But I still would appreciate, if this can be fixed somehow.

**Comment by antonWetzel** [comment]
`〜"..."` is passed to languagetool verbatim, which produces this error.
I think this is more a languagetool problem than a conversion problem.

I don't like changing code to appease the tools, but `~ "..."` with a space produces the same pdf without the error.

### Other

Does `〜` know what mono in monospace means?
```
|123|
|~~~|
|〜〜〜|

**Comment by Andrew15-5** [comment]
> I don't like changing code to appease the tools, but ~ "..." with a space produces the same pdf without the error.

Well, at least `typstfmt` doesn't remove that space, so that's nice.



> Does `〜` know what mono in monospace means?
> 
> ```
> |123|
> |~~~|
> |〜〜〜|
> ```

I don't get it (sounds like it's a joke). It's a wide char from Japanese. Since I have Japanese OS layout and that symbol isn't used outside of Japanese (in English and others), I use it as a minimalistic workaround for indent. It prints on 2 columns in terminal. It doesn't have to bet 1-column wide. All Japanese (maybe all CJK) chars are that wide.

**Comment by antonWetzel** [comment]
The char is circa 1.2 chars wide for me, it never aligns in monospace.
![image](https://github.com/antonWetzel/typst-languagetool/assets/59712243/20a344f3-0bc9-4be8-aa5c-5cde94b5a8ef)

**Comment by Andrew15-5** [comment]
I don't like that the error is saying that the quote is not paired, which is false. Can you check/see if a quote is paired? I'm just thinking that maybe adding an implicit whitespace before "left paired quote" or any "left quote" would be a good fix. Because normally you would always have a whitespace or `(` or something before left quote.

**Comment by Andrew15-5** [comment]
> The char is circa 1.2 chars wide for me, it never aligns in monospace.

Interesting. I would've never known. I normally only work in terminal, so for me, it always has a perfect width of 2:

![image](https://github.com/antonWetzel/typst-languagetool/assets/37143421/483ce234-6859-45fa-b70e-85e3af6c0ecb)

Maybe it's GitHub's way of typesetting such chars, or the whole Unicode CJK char set is rigged, I don't know.

**Comment by antonWetzel** [comment]
| ![image](https://github.com/antonWetzel/typst-languagetool/assets/59712243/dc848935-7225-41bb-8056-f4fc8896e518) | ![image](https://github.com/antonWetzel/typst-languagetool/assets/59712243/9f0a7726-efef-4423-b9b5-7202022e5425) | 
|---|---|

Typst uses `"` without a previous space not as a quotation mark, but as part of the word (like 18" Monitor). Only the show rule changes the `〜` from a word to a space and change the meaning. Without compiling the document respecting show rules is not feasible.

Languagetool handles `A"Test"` with a double missing quotation mark error, which I think is wrong. I only want to convert Typst to Languagetool input, so I don't want to create a workaround for this.

**Comment by Andrew15-5** [comment]
Understandable.
