### ISSUE TITLE
lsp error when compiling document with custom function

### ISSUE THREAD

**Issue by Eismandel** [antonWetzel/typst-languagetool#19]
Dear Anton,

I recently built a new function in typst:

```
#let mycustomday(offset) = {
 str(datetime.today(offset: (24*offset)).day()) + "." + str(datetime.today(offset: (24*offset)).month()) + "." + 
 str(datetime.today(offset:(24*offset)).year())
}
```

This function is used to create date with a positive or negative offset. When this function is not commented out, typst.languagetool throws an error:

```
Failed to compile document
	SourceDiagnostic { severity: Error, span: Span(5090655742606518), message: "unknown variable: mycustomday", trace: [Import], hints: [] }
0 Diagnostics send
```

I use typt-languagetool-lsp from vscodium buildt just an hour ago.

Any idea what I am doing wrong?

Thank you much for your support

**Comment by antonWetzel** [comment]
The offset parameter is used as the time zone, the official `typst compiler` and `typst-preview` can handle a time zone with +-24 hours. This project can't handle the offset and therefore the error.

You can offset a date by adding a `duration`:
```typst
#let my-custom-day(offset) = {
	let date = datetime.today() + duration(days: offset)
	date.display("[day].[month].[year]")
}

#my-custom-day(3)

// or inline
#(datetime.today() + duration(days: 3)).display("[day].[month].[year]")
```

This should solve the error, if not please reopen the issue.
