### ISSUE TITLE
Consecutive spaces when using `#acr`.

### ISSUE THREAD

**Issue by reitermarkus** [antonWetzel/typst-languagetool#2]
I'm using the `acrostiche` package for managing acronyms, these are not supported and trigger an error:

```
info[CONSECUTIVE_SPACES]: Two consecutive spaces
  --> main.typ:45:21
   |
45 | an #acr("IMU") and a #acr("GNSS") module may be presen
   |                     -------------- info: It seems like there are too many consecutive spaces here.
   |                                      help:  
   |
```

Ideally, the acronym (“global navigation satellite system” in this example) should be interpolated into the text before spell/grammar checking.

**Comment by antonWetzel** [comment]
I perfect fix would require a rule to replace user-defined functions with the arguments, which is pretty rare.

Maybe the shorthand solution with a rule file `typstls.json` with option `typst-lt --rules=./typstls.json` is enough.
```json5
//typstls.json
{
	"functions": {
		"acr": {
			"before": "X",
			"after": ""
		}
	}
}
```
This replaced the `acr` call with `X`, which suppressed the error for me, but lost some warnings like wrong `a` or `an`.
