### ISSUE TITLE
Remote Host Error (v0.1.0) "request could not be properly encoded"

### ISSUE THREAD

**Issue by 1dancook** [antonWetzel/typst-languagetool#26]
- On MacOS, I've installed languagetool using homebrew: `brew install languagetool`.
- I followed instructions [here](https://dev.languagetool.org/http-server.html) to start the server: `brew services start languagetool`
- I installed typst-languagetool cli with remote server feature (successful): `cargo install --git=https://github.com/antonWetzel/typst-languagetool cli --features=remote-server`
- I get a valid response from the server using their example: `http://127.0.0.1:8081/v2/check?language=en-US&text=my+text`
- However, typst-languagetool produces an error when setting the host and port.

### Error message

```
~ typst-languagetool check --host=localhost --port=8081 -p "main.typ"
Error: request could not be properly encoded: builder error for url (localhost:8081/v2/check): URL scheme is not allowed
make: *** [check] Error 1

~ typst-languagetool check --host=127.0.0.1 --port=8081 -p "main.typ"
Error: request could not be properly encoded: builder error: relative URL without a base
make: *** [check] Error 1
```

**Comment by antonWetzel** [comment]
The host requires the full URL with protocol.
