### ISSUE TITLE
Option to ignore math?

### ISSUE THREAD

**Issue by hbierlee** [antonWetzel/typst-languagetool#29]
Hi,

Another request: is there an option to ignore math (either inline or blocks)? Or is the idea to copy-paste the README block to ignore math sections?

Cheers,

Henk

**Comment by antonWetzel** [comment]
The compiled document is checked, at this point there is no difference between text from paragraphs and text from math symbols.
With the styling from the `readme` or [lt.typ](https://raw.githubusercontent.com/antonWetzel/typst-languagetool/main/example/lt.typ) equations worked for me as blocks or in a sentance without false positives.

**Comment by hbierlee** [comment]
I see! I understand this bit a lot better now.
