### ISSUE TITLE
Unable to pass InitOptions to cli

### ISSUE THREAD

**Issue by lvaroqui** [antonWetzel/typst-languagetool#34]
Hello Anton,

Thanks a lot for your work!

I have one small request (that I can tackle if you tell me how you'd want it handled), I'd like to be able to feed the CLI with the `InitOptions` just like we can with the LSP. 

It would be nice if the option was shared between LSP and CLI so that we don't have to maintain both!

**Comment by antonWetzel** [comment]
The CLI options are passed as --option=value, while the LSP options depend on your IDE's preferences.
The only way I can think of to share them is by using a file (probably in JSON format) and adding a path
argument to both.

Can you think of a better approach?

**Comment by lvaroqui** [comment]
Are you saying we can already pass arguments such as allowed world / rules to the CLI?

Yes that's what I had in mind, basically a JSON file that we could pass to both.

**Comment by lvaroqui** [comment]
Are you saying we can already pass arguments such as allowed world / rules to the CLI?

Yes that's what I had in mind, basically a JSON file that we could pass to both.

A `.typst-languagetool.json` config file would make a lot of sense IMHO.

**Comment by antonWetzel** [comment]
I added an `options` argument to the cli and the lsp to load options from a JSON file.
All common options can be in the JSON file.

All the feature flags changed names and the backend argument is now a `"backend": "bundle" | ...`.

**Comment by lvaroqui** [comment]
I just tested your changes and it seems to work well.

One thing that is sub-optimal is that for the LSP these parameters
```json
"backend": "server",
"host": "http://languagetool",
"port": "8010",
```
are required even if provided in the json file. The LSP won't start without them.

**Comment by antonWetzel** [comment]
The default for the backend was wrong and should be fixed now.

**Comment by lvaroqui** [comment]
Works great! Thanks a lot!
