### ISSUE TITLE
Update to annotate-snippet-rs to 0.11.5

### ISSUE THREAD

**Issue by lvaroqui** [antonWetzel/typst-languagetool#38]
Hello,

I faced an issue with `typst-languagetool-cli` panicking due to bad UTF-8 handling in annotate-snippet-rs.

The [issue was actually already fixed on their side but not released](https://github.com/rust-lang/annotate-snippets-rs/issues/161), now it is!

So it would be nice to update the dependencies here to get the fix!

**Comment by antonWetzel** [comment]
I updated the dependency.

Sometimes the range marker
```text
```
