### ISSUE TITLE
"Loose punctuation mark" (UNLIKELY_OPENING_PUNCTUATION) error when using inline function with `[]`

### ISSUE THREAD

**Issue by Andrew15-5** [antonWetzel/typst-languagetool#8]
```typ
Listen carefully, it will be on the test.
```

```typ
Listen #[carefully], it will be on the test.
Listen #highlight[carefully], it will be on the test.
```

![image](https://github.com/antonWetzel/typst-languagetool/assets/37143421/e78bc98e-625c-4ad4-9992-39daab181e9b)

![image](https://github.com/antonWetzel/typst-languagetool/assets/37143421/895a32b9-6c18-4a4d-9884-18c3efafb2a3)

```
1. Loose punctuation mark. [UNLIKELY_OPENING_PUNCTUATION]
```

Used 4d48a86 commit.

**Comment by antonWetzel** [comment]
The `[` and `]` were converted to "\n\n". This works for `caption: [...]` or similar, but not for `highlight[...]`.

I changed it to ignore `[` and `]`, but allow replacements for named arguments and after content based on the function.

With the rules
```json5
{
  "arguments": {
    "caption": {
      "before": "\n\n",
      "after": "\n\n",
    },
  },
  "function": {
    "table": {
      "after_argument": "\n",
    },
  },
}
```

The source
```typst
#table(
	columns: 2,
	[*Name:*], [*Test*],
	[value],   [test],
)

#figure(
	caption: [wow],
	"cool body",
)

This is #highlight[important].
```
is converted to
```
Name:
Test
value
test




wow



This is important.
```

**Comment by Andrew15-5** [comment]
So you provided an abstract overview. Looking into the code there is nothing even close to this. But changing this:

```rs
			SyntaxKind::LeftBracket | SyntaxKind::RightBracket => {
				output.add_encoded(node.text().into(), String::from("\n\n"));
			},
```

to this:

```rs
			SyntaxKind::LeftBracket | SyntaxKind::RightBracket => {
				output.add_encoded(node.text().into(), String::from(""));
			},
```

indeed removes the error. But this fix is only for one specific use case...

**Comment by antonWetzel** [comment]
https://github.com/antonWetzel/typst-languagetool/commit/194682eeea4a4f0ef9836b4e36c674c4a203a24b#diff-d42cae02d6ab6561d7a3d9a4d5538b03cdb33e075dfe41a89e70fd8206d9eaabR183-L187
This changed the behaviour to the default case with `output.add_markup(...)`, which is equalivent to `output.add_encoded(..., "")`.

If the content in the `[...]` is a seperate paragraph, with rules newlines can be inserted around the content.

**Comment by Andrew15-5** [comment]
Great now it doesn't show the error.
